version: 0.2

phases:
  pre_build:
    commands:
      - echo "Backend build started"
      - chmod +x gradlew

  build:
    commands:
      - ./gradlew clean build -x test

  post_build:
    commands:
      - mkdir -p deploy
      - cp build/libs/*.jar deploy/app.jar

artifacts:
  files:
    - deploy/app.jar
