version: 0.2

env:
  variables:
    NEXT_PUBLIC_API_URL: "http://book-app-backend-prod.eba-3tfjm3s6.ap-northeast-2.elasticbeanstalk.com"
    NODE_ENV: "production"

phases:
  install:
    runtime-versions:
      nodejs: 22
      
  pre_build:
    commands:
      - echo "Checking versions..."
      - node -v && npm -v
      
  build:
    commands:
      - echo "Build started..."
      - cd fullstack-book-app-front
      - npm ci
      - npm install --save-dev @tailwindcss/postcss postcss
      - npm run build
      
  post_build:
    commands:
      - echo "Post-build started..."
      - cd fullstack-book-app-front
      - mkdir -p .next/standalone/public
      - '[ -d public ] && cp -r public/. .next/standalone/public/ || true'
      - mkdir -p .next/standalone/.next/static
      - cp -r .next/static/. .next/standalone/.next/static/
      - cp Procfile .next/standalone/Procfile || echo "Procfile not found in current dir!"
      - '[ -d .ebextensions ] && cp -r .ebextensions .next/standalone/ || true'
      - '[ -d .platform ] && cp -r .platform .next/standalone/ || true'      
      - echo "Checking standalone directory..."
      - ls -la .next/standalone

artifacts:
  files:
    - '**/*'
  base-directory: fullstack-book-app-front/.next/standalone
  discard-paths: no
